// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR5WcWho8-9uw2njatnI5piD63xOEhQcc',
    appId: '1:287025939203:web:063368f2ac62f395915f36',
    messagingSenderId: '287025939203',
    projectId: 'flashcards-b6e18',
    authDomain: 'flashcards-b6e18.firebaseapp.com',
    storageBucket: 'flashcards-b6e18.firebasestorage.app',
    measurementId: 'G-L5N4LWFDK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk06yFDdC1IF17NzU3k7TbZXn5MWPv9UU',
    appId: '1:287025939203:android:3504011bd1c9ca4d915f36',
    messagingSenderId: '287025939203',
    projectId: 'flashcards-b6e18',
    storageBucket: 'flashcards-b6e18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH6e2BTEsC-XajjuM4VdLE7_3LCuQXpTU',
    appId: '1:287025939203:ios:bf2867b2a9e115f4915f36',
    messagingSenderId: '287025939203',
    projectId: 'flashcards-b6e18',
    storageBucket: 'flashcards-b6e18.firebasestorage.app',
    iosClientId: '287025939203-ik76du3i1aetva70r9bvjel8s51klve1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH6e2BTEsC-XajjuM4VdLE7_3LCuQXpTU',
    appId: '1:287025939203:ios:bf2867b2a9e115f4915f36',
    messagingSenderId: '287025939203',
    projectId: 'flashcards-b6e18',
    storageBucket: 'flashcards-b6e18.firebasestorage.app',
    iosClientId: '287025939203-ik76du3i1aetva70r9bvjel8s51klve1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcards',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR5WcWho8-9uw2njatnI5piD63xOEhQcc',
    appId: '1:287025939203:web:b34a0aa047ce15c5915f36',
    messagingSenderId: '287025939203',
    projectId: 'flashcards-b6e18',
    authDomain: 'flashcards-b6e18.firebaseapp.com',
    storageBucket: 'flashcards-b6e18.firebasestorage.app',
    measurementId: 'G-07KQC59QTX',
  );
}
